trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

jobs:
- job: DeployToAzureVM
  steps:
  - script: |
      sudo apt-get update
      sudo apt-get install -y apache2
    displayName: 'Install Apache'

  - task: SSH@0
    inputs:
      host: '20.0.8.103'
      port: '22'
      username: 'sandip'
      password: 'admin@1997#'
      scriptType: 'bash'
      scriptInline: |
        git clone https://github.com/mukherjeecloudsyzmil/psohtml.git
        sudo cp -r psohtml/* /var/www/html/
        sudo systemctl restart apache2
    displayName: 'Clone and Deploy HTML to Azure VM'
