trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

jobs:
- job: DeployToAzureVM
  steps:
  - checkout: self
    submodules: true

  - task: UseDotNet@2
    inputs:
      packageType: 'sdk'
      version: '3.1.x'
      installationPath: $(Agent.ToolsDirectory)/dotnet

  - script: |
      dotnet publish -c Release -o $(Build.ArtifactStagingDirectory)/publish
    displayName: 'Publish HTML project'

  - task: CopyFiles@2
    inputs:
      SourceFolder: '$(Build.ArtifactStagingDirectory)/publish'
      Contents: '**'
      TargetFolder: '$(Build.ArtifactStagingDirectory)/publish'

  - task: PublishBuildArtifacts@1
    inputs:
      pathtoPublish: '$(Build.ArtifactStagingDirectory)/publish'
      artifactName: 'publishedWebsite'
      publishLocation: 'Container'

  - task: SSH@0
    inputs:
      host: '20.0.8.103'
      port: '22'
      username: 'sandip'
      password: 'admin@1997#'
      scriptType: 'bash'
      scriptInline: |
        # Install Apache (if not already installed)
        sudo apt-get update
        sudo apt-get install -y apache2

        # Start Apache
        sudo systemctl start apache2

        # Enable Apache to start on boot
        sudo systemctl enable apache2

        # Copy HTML files to the default Apache web directory
        sudo cp -r $(System.DefaultWorkingDirectory)/publishedWebsite/* /var/www/html/

        # Restart Apache to apply changes
        sudo systemctl restart apache2
